# The lines below are called `modelines`. See `:help modeline`
# Feel free to remove those if you don't want/need to use them.
# yaml-language-server: $schema=https://goreleaser.com/static/schema-pro.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

partial:
  by: goos

report_sizes: true

env:
  - RUSTFLAGS=-C link-arg=-s
  - CARGO_TERM_COLOR=always
  - RUST_BACKTRACE=full

before:
  hooks:
    - if: '{{ eq .Runtime.Goos "darwin" }}'
      cmd: tic -xe rio -o misc misc/rio.terminfo
      output: true
    - if: '{{ eq .Runtime.Goos "windows" }}'
      cmd: dotnet tool install --global wix --version 5.0.2
      output: true
    - if: '{{ eq .Runtime.Goos "windows" }}'
      cmd: wix extension add -g WixToolset.UI.wixext/5.0.2 WixToolset.Util.wixext/5.0.2
      output: true

builds:
  - id: windows-x86_64
    builder: rust
    command: build
    flags: [--release, -p=rioterm]
    targets: [x86_64-pc-windows-msvc]

  - id: windows-arm64
    builder: rust
    command: build
    flags: [--release, -p=rioterm]
    targets: [aarch64-pc-windows-msvc]

  - id: macos
    builder: rust
    command: build
    flags: [--release, -p=rioterm]
    env:
      - MACOSX_DEPLOYMENT_TARGET={{ if eq .Arch "amd64" }}10.15{{ else }}11.0{{ end }}
    targets: [x86_64-apple-darwin, aarch64-apple-darwin]

  - id: linux-arm64-wayland
    builder: rust
    command: build
    flags: [--release, -p=rioterm, --no-default-features, --features=wayland]
    targets: [aarch64-unknown-linux-gnu]

  - id: linux-arm64-x11
    builder: rust
    command: build
    flags: [--release, -p=rioterm, --no-default-features, --features=x11]
    targets: [aarch64-unknown-linux-gnu]

  - id: linux-x64-wayland
    builder: rust
    command: build
    flags: [--release, -p=rioterm, --no-default-features, --features=wayland]
    targets: [x86_64-unknown-linux-gnu]

  - id: linux-x64-x11
    builder: rust
    command: build
    flags: [--release, -p=rioterm, --no-default-features, --features=x11]
    targets: [x86_64-unknown-linux-gnu]

release:
  make_latest: "{{ if .IsNightly }}false{{ else }}true{{ end }}"
  mode: append
  prerelease: auto
  use_existing_draft: false
  replace_existing_draft: false
  replace_existing_artifacts: true
  include_meta: false
  footer: >-
    ---
    Released by [GoReleaser](https://github.com/goreleaser/goreleaser).

nightly:
  version_template: "{{ incminor .Version }}-nightly"
  tag_name: nightly
  publish_release: true
  keep_single_release: true

changelog:
  use: git

checksum:
  name_template: checksums.txt

archives:
  - id: win-x64
    formats: [binary]
    builds: [windows-x86_64]
    name_template: "{{ .ProjectName }}-portable-x86_64"
  - id: win-arm64
    formats: [binary]
    builds: [windows-arm64]
    name_template: "{{ .ProjectName }}-portable-aarch64"

universal_binaries:
  - ids: [macos]
    replace: true

dmg:
  - name: "{{ .ProjectName }}"
    use: appbundle

notarize:
  macos_native:
    - enabled: '{{ isEnvSet "MACOS_SIGN_P12" }}'
      sign:
        identity: "Developer ID Application: Hugo Amorim"
        options: [runtime]
      notarize:
        wait: true
        keychain: "{{ .Env.KEYCHAIN_PATH }}"
        profile_name: "{{ .Env.MACOS_NOTARY_PROFILE }}"

app_bundles:
  - icon: ./misc/osx/Rio.app/Contents/Resources/icon.icns
    bundle: com.raphaelamorim.rio
    extra_files:
      - src: ./misc/72/rio
        dst: Contents/Resources/72/rio
      # releases made before goreleaser integration included the classic icon
      - src: ./misc/osx/Rio.app/Contents/Resources/icon-classic.icns
        dst: Contents/Resources/icon-classic.icns
    templated_extra_files:
      - src: ./misc/osx/Rio.app/Contents/Info.plist
        dst: Contents/Info.plist

nfpms:
  - formats: [deb, rpm]
    id: deb-arm64-wayland
    builds: [linux-arm64-wayland]
    file_name_template: "{{- trimsuffix .ConventionalFileName .ConventionalExtension -}}_wayland"
    package_name: rioterm
    dependencies: [libc6 (>= 2.35), libstdc++6 (>= 11)]
    contents:
      - src: ./misc/rio.desktop
        dst: /usr/share/applications/rio.desktop
      - src: ./misc/rio.terminfo
        dst: /usr/share/info/rio.terminfo
      - src: ./misc/logo.svg
        dst: /usr/share/icons/hicolor/scalable/apps/rio.svg
    section: admin
    priority: optional
  - formats: [deb, rpm]
    id: deb-arm64-x11
    builds: [linux-arm64-x11]
    file_name_template: "{{- trimsuffix .ConventionalFileName .ConventionalExtension -}}_x11"
    package_name: rioterm
    dependencies: [libc6 (>= 2.35), libstdc++6 (>= 11)]
    contents:
      - src: ./misc/rio.desktop
        dst: /usr/share/applications/rio.desktop
      - src: ./misc/rio.terminfo
        dst: /usr/share/info/rio.terminfo
      - src: ./misc/logo.svg
        dst: /usr/share/icons/hicolor/scalable/apps/rio.svg
    section: admin
    priority: optional
  - formats: [deb, rpm]
    id: deb-x64-wayland
    builds: [linux-x64-wayland]
    file_name_template: "{{- trimsuffix .ConventionalFileName .ConventionalExtension -}}_wayland"
    package_name: rioterm
    dependencies: [libc6 (>= 2.35), libstdc++6 (>= 11)]
    contents:
      - src: ./misc/rio.desktop
        dst: /usr/share/applications/rio.desktop
      - src: ./misc/rio.terminfo
        dst: /usr/share/info/rio.terminfo
      - src: ./misc/logo.svg
        dst: /usr/share/icons/hicolor/scalable/apps/rio.svg
    section: admin
    priority: optional
  - formats: [deb, rpm]
    id: deb-x64-x11
    builds: [linux-x64-x11]
    file_name_template: "{{- trimsuffix .ConventionalFileName .ConventionalExtension -}}_x11"
    package_name: rioterm
    dependencies: [libc6 (>= 2.35), libstdc++6 (>= 11)]
    contents:
      - src: ./misc/rio.desktop
        dst: /usr/share/applications/rio.desktop
      - src: ./misc/rio.terminfo
        dst: /usr/share/info/rio.terminfo
      - src: ./misc/logo.svg
        dst: /usr/share/icons/hicolor/scalable/apps/rio.svg
    section: admin
    priority: optional

msi:
  - id: win-x64
    name: "{{ .ProjectName }}-installer-x86_64"
    wxs: ./misc/windows/rio.wxs
    ids: [windows-x86_64]
    extensions: [WixToolset.UI.wixext, WixToolset.Util.wixext]
    extra_files: [./misc/windows/rio.ico, ./misc/windows/License.rtf]
  - id: win-arm64
    name: "{{ .ProjectName }}-installer-aarch64"
    wxs: ./misc/windows/rio.wxs
    ids: [windows-arm64]
    extensions: [WixToolset.UI.wixext, WixToolset.Util.wixext]
    extra_files: [./misc/windows/rio.ico, ./misc/windows/License.rtf]

winget:
  - use: msi
    name: Rio
    package_identifier: raphamorim.rio
    author: Raphael Amorim
    release_notes: "{{ .Changelog }}"
    release_notes_url: https://github.com/raphamorim/rio/releases/tag/{{ .Tag }}
    publisher: Raphael Amorim
    publisher_url: https://raphamorim.io
    publisher_support_url: https://github.com/raphamorim/rio/issues
    license_url: https://raw.githubusercontent.com/raphamorim/rio/main/LICENSE
    copyright: Copyright (c) {{ .Now.Format "2006" }} Raphael Amorim
    copyright_url: https://raw.githubusercontent.com/raphamorim/rio/main/LICENSE
    tags: [cross-platform, terminal, terminal-emulators]
    commit_msg_template: "New version: raphamorim.rio {{ .Tag }}"
    commit_author:
      name: raphamorim
      email: 3630346+raphamorim@users.noreply.github.com
    repository:
      owner: raphamorim
      name: winget-pkgs
      branch: rio-{{ .Tag }}-{{ .Now.Format "20060102150405"}}
      pull_request:
        enabled: true
        base:
          owner: microsoft
          name: winget-pkgs
          branch: master
        draft: false

after:
  hooks:
    - cmd: brew bump-cask-pr rio --version {{ .Version }}
      if: "{{ .IsRelease }}"
      env: ["HOMEBREW_GITHUB_API_TOKEN={{ .Env.GITHUB_TOKEN }}"]
      output: true
    - cmd: cargo publish -p rio-window
      if: "{{ .IsRelease }}"
      output: true
    - cmd: cargo publish -p sugarloaf
      if: "{{ .IsRelease }}"
      output: true
    - cmd: cargo publish -p rio-proc-macros
      if: "{{ .IsRelease }}"
      output: true
    - cmd: cargo publish -p copa
      if: "{{ .IsRelease }}"
      output: true
    - cmd: cargo publish -p corcovado
      if: "{{ .IsRelease }}"
      output: true
    - cmd: cargo publish -p teletypewriter
      if: "{{ .IsRelease }}"
      output: true
    - cmd: cargo publish -p rio-backend
      if: "{{ .IsRelease }}"
      output: true
    - cmd: cargo publish -p rioterm
      if: "{{ .IsRelease }}"
      output: true

metadata:
  maintainers: [Raphael Amorim <rapha850 at gmail dot com>]
  license: MIT
  description: A hardware-accelerated GPU terminal emulator focusing to run in desktops and browsers.
  homepage: https://raphamorim.io/rio
