[package]
name = "librio-sugarloaf"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
keywords.workspace = true
repository = "https://github.com/raphamorim/rio"
description = "Terminal renderer for librio-vt render state, powered by sugarloaf"
readme = "README.md"

[lib]
crate-type = ["rlib", "staticlib"]

[features]
default = []
capi = ["librio-vt/capi", "dep:raw-window-handle"]

[dependencies]
librio-vt = { path = "../vt", version = "0.5.0-alpha.1" }
sugarloaf = { workspace = true }
raw-window-handle = { workspace = true, optional = true }

[dev-dependencies]
rio-window = { workspace = true }
raw-window-handle = { workspace = true }
